---
image: docker:latest

stages:
  - homeassistant


# Generic Home Assistant template
.ha: &ha
  stage: homeassistant
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
#    - touch /tmp/ssl_cert
    - cp travis_secrets.yaml secrets.yaml
  script:
    - |
      python -m homeassistant \
        --config . \
        --script check_config \
        --info all

# Home Assistant test jobs
ha-latest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]
