- id: '1564951685360'
  alias: Set Theme to Slate
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
- id: Lights
  alias: Light Control
  trigger:
  - event_data: {}
    event_type: rhasspy_Light
    platform: event
  action:
    service_template: light.turn_{{ trigger.event.data["state"] }}
    data_template:
      entity_id: "{% if trigger.event.data[\"name\"] == \"guest bedroom\" %}\n  light.guest_bedroom_li_level\n\
        {% elif trigger.event.data[\"name\"] == \"family room\" %}\n  light.family_room\
        \   \n{% elif trigger.event.data[\"name\"] == \"master bedroom\" %} \n  light.master_bedroom_l_level\n\
        {% elif trigger.event.data[\"name\"] == \"master bathroom\" %} \n  light.master_bathroom\n\
        {% elif trigger.event.data[\"name\"] == \"breakfast table\" %} \n  light.breakfast_table\n\
        {% endif %}      \n"
