- id: '1564951685360'
  alias: Set Theme to Slate
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
- id: Lights
  alias: Light Control
  trigger:
  - event_data: {}
    event_type: rhasspy_Light
    platform: event
  action:
    service_template: light.turn_{{ trigger.event.data["state"] }}
    data_template:
      entity_id: "{% if trigger.event.data[\"name\"] == \"guest bedroom\" %}\n  light.guest_bedroom_li_level\n\
        {% elif trigger.event.data[\"name\"] == \"family room\" %}\n  light.family_room\
        \   \n{% elif trigger.event.data[\"name\"] == \"master bedroom\" %} \n  light.master_bedroom_l_level\n\
        {% elif trigger.event.data[\"name\"] == \"master bathroom\" %} \n  light.master_bathroom\n\
        {% elif trigger.event.data[\"name\"] == \"breakfast table\" %} \n  light.breakfast_table\n\
        {% endif %}      \n"
- id: Spotify
  alias: Spotify Control
  trigger:
  - event_data: {}
    event_type: rhasspy_PlaySpotify
    platform: event
  action:
  - service: media_player.select_source
    data_template:
      entity_id: media_player.spotify
      source: "{% if trigger.event.data[\"name\"] == \"basement\" %} \n  Basement\n\
        {% elif trigger.event.data[\"name\"] == \"alexa\" %} \n  Alexa\n{% elif trigger.event.data[\"\
        name\"] == \"family room\" %} \n  Roku\n{% endif %}\n"
  - service: media_player.play_media
    data_template:
      entity_id: media_player.spotify
      media_content_id: "{% if trigger.event.data[\"genre\"] == \"music\" %} \n  spotify:playlist:2Y3kAZMPvtAr3VP96876AB\n\
        {% elif trigger.event.data[\"name\"] == \"songs\" %} \n  spotify:playlist:2Y3kAZMPvtAr3VP96876AB\n\
        {% elif trigger.event.data[\"genre\"] == \"buddha bar\" %} \n  spotify:playlist:5p495waCXrUHkKrbErPoBv\n\
        {% elif trigger.event.data[\"genre\"] == \"kids music\" %} \n  spotify:playlist:4n3JDJF0Np7Rp0qwxjwbnW\n\
        {% elif trigger.event.data[\"genre\"] == \"hindi\" %} \n  spotify:playlist:37i9dQZF1DWTwzVdyRpXm1\n\
        {% elif trigger.event.data[\"genre\"] == \"top hits\" %} \n  spotify:playlist:37i9dQZF1DXcBWIGoYBM5M\n\
        {% elif trigger.event.data[\"genre\"] == \"eighties\" %} \n  spotify:playlist:2Y3kAZMPvtAr3VP96876AB\n\
        {% elif trigger.event.data[\"genre\"] == \"piano music\" %} \n  spotify:playlist:37i9dQZF1DX7K31D69s4M1\n\
        {% elif trigger.event.data[\"genre\"] == \"classic pop\" %} \n  spotify:playlist:37i9dQZF1DX4v0Y84QklHD\n\
        {% elif trigger.event.data[\"genre\"] == \"down tempo\" %} \n  spotify:playlist:37i9dQZF1DWWQp0YMTvpD3\
        \           \n{% elif trigger.event.data[\"genre\"] == \"something\" %} \n\
        \  spotify:playlist:34eaogIEYzSONwt2GTAaCE\n{% endif %}\n"
      media_content_type: playlist
- id: SpotifyNextTrack
  alias: Spotify Next Song
  trigger:
  - event_data: {}
    event_type: rhasspy_SpotifyNextTrack
    platform: event
  action:
  - service: media_player.media_next_track
    data_template:
      entity_id: media_player.spotify
- id: SpotifyPlayPause
  alias: Spotify Pause-Stop
  trigger:
  - event_data: {}
    event_type: rhasspy_SpotifyPlayPause
    platform: event
  action:
  - service: media_player.media_play_pause
    data_template:
      entity_id: media_player.spotify
