config: #show config wrench as default_config removed to hide map & history
my:
logbook: #show logbook as default_config removed to hide map & history
history: #add history back to see graphs :(
homeassistant:
  country: 'US'
  name: Home 
  temperature_unit: F
  latitude: !secret home_latitude
  longitude: !secret home_longitude
#  elevation: !secret home_elevation
  internal_url: !secret baseurl
  external_url: !secret baseurl
  unit_system: imperial
#  time_zone: !secret time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/tmp/'
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
cloud:
# Example configuration.yaml entry
api:
# enable the recorder integration (optional)
recorder:

frontend:
  themes: !include_dir_merge_named themes/
# Example configuration.yaml entry

discovery:
mobile_app:
ios:


# Text to speech
lovelace:
  mode: yaml
  resources:  !include resources.yaml
  
readme:

tts:
  - platform: google_translate
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com


spotify:
  client_id: !secret client_id_spotify
  client_secret: !secret client_secret_spotify



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
# hacs:
#   token: !secret hacs_token

#hue:
#  bridges:
#    - host: !secret hue_ip  

roku:
- host: !secret roku_ip

#alarm_control_panel:
#  platform: alarmdotcom
#  platform: alarmdotcomajax
#  username: !secret alarm_user
#  password: !secret alarm_pass
#  two_factor_cookie: !secret alarm_cookie


# Example configuration.yaml entry
input_number:
  pantry_expiration:
    name: Pantry Expiration Days
    initial: 90
    min: 30
    max: 120
    step: 1



sensor:  
#   - platform: airthings_wave
#     mac: "98:07:2D:4A:97:5C"
# #    name: 'Basement Airthings Wave'
#     scan_interval: 120
# Example configuration.yaml entry

###Github
  - platform: github
    access_token: !secret githubtoken
    repositories:
      - path: !secret github_path
      
      
###Travis CI
  - platform: travisci
    api_key: !secret travisci_token
    # repository:
    #   - upgraded-couscous
    # monitored_conditions:
    #   - last_build_id
    #   - last_build_duration
    #   - last_build_finished_at
    #   - last_build_started_at
    #   - last_build_state
    #   - state
      

pi_hole:
  host: !secret pi_hole_ip

media_source:

# logger:
#   default: debug
#  logs:
#    homeassistant.components.darksky: debug
#    homeassistant.components.alarmdotcom: debug   

# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


rachio:
  api_key: !secret rachio_key


# Example configuration.yaml entry
device_tracker:
  - platform: bluetooth_le_tracker
  
# Example configuration.yaml entry
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password


# Example configuration.yaml entry
withings:
  client_id: !secret withingsid
  client_secret: !secret withingssecret

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple

# panel_iframe:
#   unraid:
#     title: 'unRAID'
#     url: !secret unraid
#     icon: 'mdi:alpha-u-box-outline'

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_url

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave
    
