config: #show config wrench as default_config removed to hide map & history
my:
logbook: #show logbook as default_config removed to hide map & history
history: #add history back to see graphs :(
homeassistant:
  country: 'US'
  name: Home
  temperature_unit: F
  latitude: !secret home_latitude
  longitude: !secret home_longitude
#  elevation: !secret home_elevation
  internal_url: !secret baseurl
  external_url: !secret baseurl
  unit_system: imperial
#  time_zone: !secret time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/tmp/'
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
cloud:
# Example configuration.yaml entry
api:
# enable the recorder integration (optional)
recorder:

frontend:
  themes: !include_dir_merge_named themes/
# Example configuration.yaml entry

# discovery:
mobile_app:
ios:

# Example configuration.yaml entry
assist_pipeline:

# Text to speech
lovelace:
  mode: yaml
  resources:  !include resources.yaml

readme:

tts:
  - platform: google_translate


# spotify:
#   client_id: !secret client_id_spotify
#   client_secret: !secret client_secret_spotify

# Example configuration.yaml entry with optional parameters
feedreader:
  urls:
    - https://rss.nytimes.com/services/xml/rss/nyt/PersonalTech.xml
  scan_interval:
    minutes: 1
  max_entries: 5


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Example configuration.yaml entry
input_number:
  pantry_expiration:
    name: Pantry Expiration Days
    initial: 90
    min: 30
    max: 120
    step: 1

media_source:

# Example configuration.yaml entry
media_player:
  - platform: aquostv
    host: !secret mastebedroomtvip

# logger:
#   default: debug
#  logs:
#    homeassistant.components.darksky: debug

# Example configuration.yaml entry
device_tracker:
  - platform: bluetooth_le_tracker
  - platform: unifi_direct
    host: !secret unifi_router
    username: !secret unifi_user
    password: !secret unifi_pass


# Example configuration.yaml entry
withings:
  client_id: !secret withingsid
  client_secret: !secret withingssecret

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_url
