views:
  - !include '/config/views/status.yaml'
  - !include '/config/views/cameras.yaml'
  - !include '/config/views/basement.yaml'
  - !include '/config/views/mainlevel.yaml'
  - !include '/config/views/upstairs.yaml'
  - !include '/config/views/devices.yaml'
  - !include '/config/views/media.yaml'
  - !include '/config/views/level.yaml'
#  - !include '/config/views/news.yaml'
  - !include '/config/views/issues.yaml'
#  - !include '/config/views/floor_01.yaml'
#  - !include '/config/views/system.yaml'
  - !include '/config/views/monitoring.yaml'
  - !include '/config/views/octoprint.yaml'
  
#background: center / cover no-repeat url("/local/blackgrey.jpg") fixed
button_card_templates:

  cover:
    layout: icon_label
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 30px
        - width: 30px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      label:
        - font-size: 10px
        - font-weight: normal

      lock:
        - align-items: flex-end
    state:
      - value: "open"
        styles:
          card:
            - --paper-card-background-color: rgba(40, 40, 40)
            - box-shadow: 0px 0px 10px 3px var(--button-card-light-color)
          name:
            - color: white
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  windows-doors:
    layout: icon_label
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 30px
        - width: 30px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      lock:
        - align-items: flex-end
      label:
        - font-size: 10px
        - font-weight: normal

    state:
      - value: "on"
        styles:
          card:
            - --paper-card-background-color: rgba(40, 40, 40)
            - box-shadow: 0px 0px 10px 3px var(--button-card-light-color)
          name:
            - color: white
  lights:
    layout: icon_label
    icon: mdi:fire
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 42px
        - width: 42px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      label:
        - font-size: 10px
        - font-weight: normal
      lock:
        - align-items: flex-end
    size: 100%
    state:
      - value: "on"
        styles:
          card:
            - --paper-card-background-color: rgba(30, 30, 30)
            - box-shadow: 0px 0px 20px 3px var(--button-card-light-color)
          name:
            - color: white
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  windows-doors-2:
    layout: icon_label
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 7px auto 7px
        - grid-template-columns: 7px auto
      card:
        - border-radius: 7px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 4px
        - width: 4px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 3px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      lock:
        - align-items: flex-end
      label:
        - font-size: 8px
        - font-weight: normal
    state:
      - value: "on"
        styles:
          card:
            - --paper-card-background-color: rgba(40, 40, 40)
            - box-shadow: 0px 0px 10px 3px var(--button-card-light-color)
          name:
            - color: white      
  lights_inset:
#    layout: icon_label
    icon: mdi:fire
    size: 30% # You can adjust the size of the icon
    styles:
      img_cell:
        - padding-left: 25px # You can adjust padding of the icon
        - justify-content: start
      card:
        - width: min(25vw, 100px)
        - height: min(25vw, 100px)
        - border-radius: 15px
        - border-style: solid
        - border-color: var(--primary-background-color)
        - border-width: 1px
        - margin: 10px
        - box-shadow: |
            [[[ return states['light.family_room'].state == 'off'
              ? '-5px -5px 8px rgba(50, 50, 50, .2), 5px 5px 8px rgba(0, 0, 0, .08)'
              : '-4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0, .03)';
            ]]]
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
      grid:
        - grid-template-areas: '"i" "n" "s"'
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      name:
        - justify-self: start
        - font-weight: bold
        - font-size: 15px
        - padding-left: 15px
      state:
        - justify-self: start
        - font-weight: bold
        - font-size: 15px
        - opacity: 0.6
        - padding: 0 15px 5px
    show_state: true
    state:
      - value: 'on'
        styles:
          card:
            - border-width: 2px
            - box-shadow: |
                [[[ return states['light.family_room'].state == 'off'
                  ? 'inset -4px -4px 5px rgba(60, 60, 60, .6), inset 4px 4px 5px rgba(0, 0, 0, .5)'
                  : 'inset -3px -3px 5px rgba(255, 255, 255), inset 3px 3px 5px rgba(0, 0, 0, .08)';
                ]]]
            - border-color: var(--paper-item-icon-active-color)
          icon:
            - color: var(--paper-item-icon-active-color)
    tap_action:
      action: toggle
      haptic: light
    hold_action:
      action: more-info
      haptic: medium           
