views:
  - !include '/config/views/status.yaml'
  - !include '/config/views/cameras.yaml'
  - !include '/config/views/basement.yaml'
  - !include '/config/views/mainlevel.yaml'
  - !include '/config/views/upstairs.yaml'
  - !include '/config/views/devices.yaml'
  - !include '/config/views/media.yaml'
  - !include '/config/views/level.yaml'
  - !include '/config/views/news.yaml'
  - !include '/config/views/issues.yaml'

custom_header:
  split_mode: true
  footer_mode: true
  header_text: >-
    <style>
    #flipper {color:#999;}
    #flip {height:24px;overflow:hidden;}
    #flip > div > div {color:#fff;height:24px;margin-bottom:24px;display:inline-block;}
    #flip div:first-child {animation: show 10s linear infinite;}
    @keyframes show {
    0% {margin-top:-144px;}
    5% {margin-top:-96px;}
    33% {margin-top:-96px;}
    38% {margin-top:-48px;}
    66% {margin-top:-48px;}
    76% {margin-top:0px;}
    100% {margin-top:0px;}}
    #flipper p {position:fixed;color:#999; }
    </style>
    <div id=flipper><div id=flip><div><div>
    Trash day is {{states('sensor.trash')}}</div></div><div><div>
    House is {% if is_state("alarm_control_panel.alarm_com", "disarmed") -%} Disarmed {%- elif is_state("alarm_control_panel.alarm_com", "armed_home") -%}  Armed (Stay) {%- elif is_state("alarm_control_panel.alarm_com", "armed_away") -%} Armed (Away) {%- endif %}</div></div><div><div>
    {% if is_state("media_player.spotify_1235664265", "playing") -%} Currently playing {{state_attr('media_player.spotify_1235664265', 'media_title')}} by {{state_attr('media_player.spotify_1235664265', 'media_artist')}} on {{state_attr('media_player.spotify_1235664265', 'source')}} {%- endif %}</div></div><div><div> 
    Trash day is {{states('sensor.trash')}}</div></div><div><div>



          


background: center / cover no-repeat url("/local/blackgrey.jpg") fixed
button_card_templates:

  cover:
    layout: icon_label
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 30px
        - width: 30px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      label:
        - font-size: 10px
        - font-weight: normal

      lock:
        - align-items: flex-end
    state:
      - value: "open"
        styles:
          card:
            - --paper-card-background-color: rgba(40, 40, 40)
            - box-shadow: 0px 0px 10px 3px var(--button-card-light-color)
          name:
            - color: white
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  windows-doors:
    layout: icon_label
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 30px
        - width: 30px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      lock:
        - align-items: flex-end
      label:
        - font-size: 10px
        - font-weight: normal

    state:
      - value: "on"
        styles:
          card:
            - --paper-card-background-color: rgba(40, 40, 40)
            - box-shadow: 0px 0px 10px 3px var(--button-card-light-color)
          name:
            - color: white
  lights:
    layout: icon_label
    icon: mdi:fire
    color: auto
    aspect_ratio: 1/1
    show_state: false
    show_name: true
    show_label: false
    show_last_changed: true
    styles:
      grid:
        - grid-template-rows: 42px auto 42px
        - grid-template-columns: 42px auto
      card:
        - border-radius: 15px
        - margin: 5px 5px 0px 0px
        - padding: 0px 0px
      icon:
        - height: 42px
        - width: 42px
      name:
        - justify-self: start
        - padding: 0px 10px
        - font-size: 13px
        - font-family: Helvetica
        - text-transform: capitalize
        - font-weight: bold
        - align-self: end
      label:
        - font-size: 10px
        - font-weight: normal
      lock:
        - align-items: flex-end
    size: 100%
    state:
      - value: "on"
        styles:
          card:
            - --paper-card-background-color: rgba(30, 30, 30)
            - box-shadow: 0px 0px 20px 3px var(--button-card-light-color)
          name:
            - color: white
    tap_action:
      action: toggle
    hold_action:
      action: more-info
              
