
input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Clean
    
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Running
      - Idle
      - Clean
    initial: Idle


sensor:
  - platform: template
    sensors:
      washer_amps:
        friendly_name_template: "{{ states.switch.washer.name}} Current"
        value_template: '{{ states.switch.washer.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      washer_watts:
        friendly_name_template: "{{ states.switch.washer.name}} Current Consumption"
        value_template: '{{ states.switch.washer.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      washer_total_kwh:
        friendly_name_template: "{{ states.switch.washer.name}} Total Consumption"
        value_template: '{{ states.switch.washer.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washer_volts:
        friendly_name_template: "{{ states.switch.washer.name}} Voltage"
        value_template: '{{ states.switch.washer.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      washer_today_kwh:
        friendly_name_template: "{{ states.switch.washer.name}} Today's Consumption"
        value_template: '{{ states.switch.washer.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'


