name: Home Assistant CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 2 * * *

jobs:
  #YAML Lint
  yamllint:
    name: 🧹 YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1.4

  #Remark Lint
  remarklint:
    name: 🧹 Remark Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  #Home Assistant - Config check
  home_assistant:
    name: "🏠 Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
#    needs: [yamllint, remarklint]
    needs: [remarklint]
    strategy:
      fail-fast: false
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: ➕ Create dummy files
        run: |
          touch ./home-assistant.log
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.4
        with:
          path: "./"
          secrets: travis_secrets.yaml
          version: "${{ matrix.version }}"
